Images python 3.13

diff --git a/Dockerfile.slim b/Dockerfile.slim
--- a/Dockerfile.slim
+++ b/Dockerfile.slim
@@ -1,40 +1,68 @@
 # Dockerfile.slim
-# version: 24.10.1
+# version: 24.11.1
+#
+# Riverbed SteelScript, https://github.com/riverbed/steelscript
+#
+# Usage
+#   
+#   # Build
+#
+#       docker build --tag steelscript.slim:latest -f Dockerfile.slim .
+#
+#   # Run
+#       
+#      docker run --rm steelscript.slim:latest steel
 
-# start with slim version
-FROM python:3.12-slim
+# Use a slim image
+FROM python:3.13-slim
 LABEL org.opencontainers.image.authors="Riverbed Community"
 LABEL org.opencontainers.image.source="https://github.com/riverbed/steelscript"
+LABEL org.opencontainers.image.title="SteelScript - slim image"
+LABEL org.opencontainers.image.version="24.11.1"
 
-RUN set -ex \
-        && install=' \
+RUN set -ex && \
+        # Install deps for build
+        buildDeps=' \
                 git \
-                less \
-                vim \
+                gcc \
                 libpcap-dev \
-        ' \
-        && apt-get update && apt-get install -y $install --no-install-recommends && rm -rf /var/lib/apt/lists/*
+        ' && \
+        apt-get update && \ 
+        apt-get upgrade -y && \         
+        apt-get install -y $buildDeps --no-install-recommends && \
+        rm -rf /var/lib/apt/lists/* && \
+        # Install SteelScript and modules, latest versions
+        pip install --no-cache-dir --upgrade pip && \
+        pip install --no-cache-dir \
+        git+https://github.com/riverbed/steelscript \
+        git+https://github.com/riverbed/steelscript-netprofiler \
+        git+https://github.com/riverbed/steelscript-wireshark \
+        git+https://github.com/riverbed/steelscript-cmdline \
+        git+https://github.com/riverbed/steelscript-scc \
+        git+https://github.com/riverbed/steelscript-appresponse \
+        git+https://github.com/riverbed/steelscript-netim \
+        git+https://github.com/riverbed/steelscript-client-accelerator-controller \            
+        git+https://github.com/riverbed/steelscript-steelhead \
+        git+https://github.com/riverbed/steelscript-packets && \
+        # Cleanup, purging build deps
+        distroExtra=' \
+                perl \
+                linux-libc-dev \
+        ' && \                
+        apt-get remove -y --purge --autoremove $buildDeps $distroExtra && \
+        apt-get autoremove && \
+        apt-get clean && \
+        rm -rf ~/.cache
 
-RUN set -ex \
-        && buildDeps=' \
-                g++ \
-                libssl-dev \
-                libffi-dev \
-        ' \
-        && apt-get update && apt-get install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/* \
-        \
-        && pip install --src /src \
-            -e git+https://github.com/riverbed/steelscript#egg=steelscript \
-            -e git+https://github.com/riverbed/steelscript-netprofiler#egg=steelscript-netprofiler \
-            -e git+https://github.com/riverbed/steelscript-wireshark#egg=steelscript-wireshark \
-            -e git+https://github.com/riverbed/steelscript-cmdline#egg=steelscript-cmdline \
-            -e git+https://github.com/riverbed/steelscript-scc#egg=steelscript-scc \
-            -e git+https://github.com/riverbed/steelscript-appresponse#egg=steelscript-appresponse \
-            -e git+https://github.com/riverbed/steelscript-netim.git#egg=steelscript-netim \
-            -e git+https://github.com/riverbed/steelscript-client-accelerator-controller#egg=steelscript-cacontroller \            
-        && pip install --src /src \
-            -e git+https://github.com/riverbed/steelscript-steelhead#egg=steelscript-steelhead \
-            -e git+https://github.com/riverbed/steelscript-packets.git@master#egg=steelscript-packets \
-        && rm -f /src/pip-delete-this-directory.txt \
-        && apt-get purge -y --auto-remove $buildDeps \
-        && rm -rf ~/.cache
+# Create a non-root user and group
+ARG USER_ID=1000
+ARG GROUP_ID=$USER_ID
+RUN groupadd --gid $GROUP_ID steelscript && useradd --create-home --home-dir /steelscript --gid $GROUP_ID --uid $USER_ID steelscript
+USER steelscript
+
+# Create SteelScript workspace
+RUN set -ex && steel mkworkspace -d /steelscript/workspace
+WORKDIR /steelscript/workspace
+
+# Configure container startup
+CMD ["/bin/bash"]
